# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 05:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('major', models.CharField(max_length=40, verbose_name='전공선택/관심분야')),
                ('date', models.CharField(max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
                ('area', models.CharField(max_length=20, verbose_name='멘토링 지역')),
                ('is_recommended', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
                ('author', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_intro', models.TextField(max_length=500, verbose_name='학과 소개')),
                ('time_manage', models.TextField(max_length=500, verbose_name='계획표 세우는 법')),
                ('grade_manage', models.TextField(max_length=500, verbose_name='내신 관리 비법')),
                ('subject_study', models.TextField(max_length=500, verbose_name='과목 별 공부법')),
                ('know_how', models.TextField(max_length=500, verbose_name='본인만의 특별한 공부법')),
                ('delivering_message', models.TextField(max_length=500, verbose_name='그 외에 전달하고 싶은 메세지')),
                ('mentor', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mentoring', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mentoring.Mentoring')),
            ],
        ),
    ]
