# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('mentoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoring',
            name='acceptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
