# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0004_mentoring_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendmentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=40)),
                ('career', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
