# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0005_recommendmentor_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='photo',
        ),
        migrations.AddField(
            model_name='review',
            name='photo1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='review',
            name='photo2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='review',
            name='photo3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='review',
            name='photo4',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='review',
            name='photo5',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='review',
            name='photo6',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
