# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0008_auto_20160404_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoring',
            name='date',
            field=models.CharField(max_length=20, verbose_name='희망 날짜'),
        ),
        migrations.AlterField(
            model_name='mentoring',
            name='major1',
            field=models.CharField(max_length=40, verbose_name='관심전공1'),
        ),
        migrations.AlterField(
            model_name='mentoring',
            name='major2',
            field=models.CharField(max_length=40, verbose_name='관심전공2'),
        ),
        migrations.AlterField(
            model_name='mentoring',
            name='major3',
            field=models.CharField(max_length=40, verbose_name='관심전공3'),
        ),
        migrations.AlterField(
            model_name='mentoring',
            name='rating',
            field=models.CharField(max_length=20, verbose_name='성적수준'),
        ),
    ]
