# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0009_auto_20160407_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoring',
            name='acceptor',
            field=models.CharField(default='1', max_length=20, verbose_name='멘토 전화번호'),
        ),
    ]
