# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0012_auto_20160416_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoring',
            name='will_to_study',
            field=models.CharField(choices=[('아주 높은 편', '아주 높은 편'), ('높은 편', '높은 편'), ('중간 정도', '중간 정도'), ('낮은 편', '낮은 편'), ('아주 낮은 편', '아주 낮은 편')], max_length=30, verbose_name='공부의욕'),
        ),
    ]
