# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 15:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0013_auto_20160420_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='answering_question',
            field=models.TextField(default=datetime.datetime(2016, 4, 20, 15, 36, 46, 372503, tzinfo=utc), max_length=500, verbose_name='학생의 질문에 대한 답변'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='mentor_intro',
            field=models.TextField(default=datetime.datetime(2016, 4, 20, 15, 36, 54, 141482, tzinfo=utc), max_length=500, verbose_name='멘토 소개 문구'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='mentor_spec',
            field=models.TextField(default=datetime.datetime(2016, 4, 20, 15, 36, 57, 123421, tzinfo=utc), max_length=500, verbose_name='약 력'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='delivering_message',
            field=models.TextField(max_length=500, verbose_name='그 외에 학생에게 전달하고 싶은 메세지'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='know_how',
            field=models.TextField(max_length=500, verbose_name='기타 알려주고 싶은 본인만의 특별한 공부법'),
        ),
    ]
