# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0014_auto_20160421_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='subject_study',
            field=models.TextField(max_length=500, verbose_name='과목별 공부법'),
        ),
    ]
