# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 05:30
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('major', models.CharField(choices=[('간호대학', '간호대학'), ('경영대학', '경영대학'), ('농경제사회학부', '농경제사회학부'), ('사회과학계열', '사회과학계열'), ('소비자아동학부', '소비자아동학부'), ('의류학과', '의류학과'), ('인문계열', '인문계열'), ('국어교육과', '국어교육과'), ('물리교육과', '물리교육과'), ('사회교육과', '사회교육과'), ('생물교육과', '생물교육과'), ('역사교육과', '역사교육과'), ('영어교육과', '영어교육과'), ('지구과학교육과', '지구과학교육과'), ('지리교육과', '지리교육과'), ('체육교육과', '체육교육과'), ('화학교육과', '화학교육과'), ('건축학과', '건축학과'), ('물리천문학부', '물리천문학부'), ('바이오시스템소재학부', '바이오시스템소재학'), ('산림과학부', '산림과학부'), ('생명과학부', '생명과학부'), ('수리과학부', '수리과학부'), ('식물생산과학부', '식물생산과학부'), ('식품영양학과', '식품영양학과'), ('응용생물화학부', '응용생물화학부'), ('화학부', '화학부'), ('건설환경공학부', '건설환경공학부'), ('기계항공공학부', '기계항공공학부'), ('산업공학과', '산업공학과'), ('식품동물생명공학부', '식품동물생명공학부'), ('재료공학부', '재료공학부'), ('전기정보공학부', '전기정보공학부'), ('조경지역시스템공학부', '조경지역시스템공학부'), ('조선해양공학과', '조선해양공학과'), ('컴퓨터공학부', '컴퓨터공학부'), ('화학생물공학부', '화학생물공학부'), ('의예과', '의예과')], default='', max_length=40, verbose_name='전공')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='전화번호')),
                ('admission_type', models.CharField(choices=[('지역균형선발전형', '지역균형선발전형'), ('일반전형(특기자)', '일반전형(특기자)'), ('기회균형선발특별전형', '기회균형선발특별전형')], default='', max_length=40, verbose_name='입학 전형')),
                ('is_mentor', models.BooleanField(default=False)),
                ('frequency', models.IntegerField(default=0)),
                ('rating', models.FloatField(blank=True, default=0)),
                ('image', models.ImageField(blank=True, upload_to=accounts.models.random_name_upload_to, verbose_name='사진 업로드')),
                ('intro', models.TextField(max_length=300, verbose_name='간단한 자기소개')),
                ('grade', models.CharField(max_length=20, verbose_name='학년')),
                ('access_route', models.CharField(max_length=80, verbose_name='가입경로')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
