# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='admission_type',
            field=models.CharField(choices=[('지역균형선발전형', '지역균형선발전형'), ('일반전형(특기자)', '일반전형(특기자)'), ('기회균형선발특별전형', '기회균형선발특별전형'), ('정시전형', '정시전형')], default='', max_length=40, verbose_name='입학 전형'),
        ),
    ]
