# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160402_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='intro',
            field=models.TextField(max_length=300, verbose_name='기타 약력'),
        ),
    ]
