# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160402_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='highschool',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_route',
            field=models.CharField(choices=[('지인소개', '지인소개'), ('학원소개', '학원소개'), ('페이스북', '페이스북'), ('네이버', '네이버'), ('전단지', '전단지'), ('기타', '기타')], max_length=80, verbose_name='가입경로'),
        ),
    ]
